In [1]:
from sklearn import datasets
iris = datasets.load_iris()

In [2]:
iris.keys()

dict_keys(['data', 'feature_names', 'target_names', 'target', 'DESCR'])

In [3]:
iris.data.shape

(150, 4)

In [4]:
digits = datasets.load_digits()
digits.keys()

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])

In [5]:
digits.data.shape

(1797, 64)

In [6]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [7]:
import numpy as np
from sklearn import datasets

In [8]:
iris = datasets.load_iris()
iris_x = iris.data
iris_y = iris.target

In [9]:
np.random.seed(0)
indices = np.random.permutation(len(iris_x))

In [10]:
iris_x_train = iris_x[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_x_test  = iris_x[indices[-10:]]
iris_y_test  = iris_y[indices[-10:]]

In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(iris_x_train, iris_y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [42]:
knn.predict(iris_x_test)

array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])

In [43]:
iris_y_test

array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])