In [3]:
from sklearn import datasets
digits = datasets.load_digits()

In [6]:
digits.data

array([[  0.,   0.,   5., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,  10.,   0.,   0.],
       [  0.,   0.,   0., ...,  16.,   9.,   0.],
       ..., 
       [  0.,   0.,   1., ...,   6.,   0.,   0.],
       [  0.,   0.,   2., ...,  12.,   0.,   0.],
       [  0.,   0.,  10., ...,  12.,   1.,   0.]])

In [8]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [10]:
digits.images[0]

array([[  0.,   0.,   5.,  13.,   9.,   1.,   0.,   0.],
       [  0.,   0.,  13.,  15.,  10.,  15.,   5.,   0.],
       [  0.,   3.,  15.,   2.,   0.,  11.,   8.,   0.],
       [  0.,   4.,  12.,   0.,   0.,   8.,   8.,   0.],
       [  0.,   5.,   8.,   0.,   0.,   9.,   8.,   0.],
       [  0.,   4.,  11.,   0.,   1.,  12.,   7.,   0.],
       [  0.,   2.,  14.,   5.,  10.,  12.,   0.,   0.],
       [  0.,   0.,   6.,  13.,  10.,   0.,   0.,   0.]])

In [11]:
from sklearn import svm

In [12]:
clf = svm.SVC(gamma=0.001, C=100.)

In [13]:
clf.fit(digits.data[:-1], digits.target[:-1])

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [14]:
clf.predict(digits.data[-1:])

array([8])

In [31]:
# save and restore with pickle
import pickle
s = pickle.dumps(clf)
clf2 = pickle.loads(s)
clf2.predict(digits.data[-1:])
s

b'\x80\x03csklearn.svm.classes\nSVC\nq\x00)\x81q\x01}q\x02(X\r\x00\x00\x00class_weight_q\x03cnumpy.core.multiarray\n_reconstruct\nq\x04cnumpy\nndarray\nq\x05K\x00\x85q\x06C\x01bq\x07\x87q\x08Rq\t(K\x01K\n\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00f8q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89CP\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?q\x11tq\x12bX\x01\x00\x00\x00Cq\x13G@Y\x00\x00\x00\x00\x00\x00X\x07\x00\x00\x00_sparseq\x14\x89X\x07\x00\x00\x00epsilonq\x15G\x00\x00\x00\x00\x00\x00\x00\x00X\n\x00\x00\x00shape_fit_q\x16M\x04\x07K@\x86q\x17X\x10\x00\x00\x00_sklearn_versionq\x18X\x06\x00\x00\x000.18.1q\x19X\x08\x00\x00\x00max_iterq\x1aJ\xff\xff\xff\xffX\x0b\x00\x00\x00_dual_coef_

In [30]:
# save and restore with pickle
from sklearn.externals import joblib
joblib.dump(clf, 'test.pkl')
clf2 = joblib.load('test.pkl')
clf2.predict(digits.data[-1:])

array([8])