In [1]:
from sklearn import datasets
iris = datasets.load_iris()

In [5]:
iris.keys()

dict_keys(['feature_names', 'data', 'target_names', 'DESCR', 'target'])

In [16]:
iris.data.shape

(150, 4)

In [19]:
digits = datasets.load_digits()
digits.keys()

dict_keys(['target', 'data', 'target_names', 'DESCR', 'images'])

In [24]:
digits.data.shape

(1797, 64)

In [30]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [31]:
import numpy as np
from sklearn import datasets

In [35]:
iris = datasets.load_iris()
iris_x = iris.data
iris_y = iris.target

In [39]:
np.random.seed(0)
indices = np.random.permutation(len(iris_x))

In [40]:
iris_x_train = iris_x[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_x_test  = iris_x[indices[-10:]]
iris_y_test  = iris_y[indices[-10:]]

In [41]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(iris_x_train, iris_y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [42]:
knn.predict(iris_x_test)

array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])

In [43]:
iris_y_test

array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])