In [21]:
import numpy as np
import pandas as pd
%matplotlib inline

In [43]:
train_data = np.load('normal.npy')
input = np.empty(0)
output = np.empty(0)

for i in range(3):
    part = train_data[i:i+3]
    print(part)
    input = np.append(input, part[:, 0])
    output = np.append(output, part[-1, 1])
input.reshape(-1, 3, 1)
output.reshape(-1, 1)

[[ 0.          0.12533323]
 [ 0.12533323  0.24868989]
 [ 0.24868989  0.36812455]]
[[ 0.12533323  0.24868989]
 [ 0.24868989  0.36812455]
 [ 0.36812455  0.48175367]]
[[ 0.24868989  0.36812455]
 [ 0.36812455  0.48175367]
 [ 0.48175367  0.58778525]]


array([[ 0.36812455],
       [ 0.48175367],
       [ 0.58778525]])